GPIOTE
IEHIQ/ESTC-project pull request #13
Opened 2021-11-16 13:13 UTC by IEHIQ

2021-11-17 12:17 UTC, Diadlo requested changes
Рекомендую подумать над тем, чтобы реструктурировать код. Вынести большие куски логики из основного цикла в функции + вынести в отдельные .c/.h файлы однотипные блоки. Типа работы с кнопкой, светодиодами и т.п.

2021-11-17 12:17 UTC, Diadlo commented on main.c
> +uint32_t dclick_time_left = 0;
Пожалуйста, если переменная обозначает какую-то физическую виличину, добавляйте размерность в имя

2021-11-17 12:17 UTC, Diadlo commented on main.c
> +    nrfx_gpiote_in_config_t button_config;
1. Вроде конфиг используются и настраивается только в `button_init`. Почему бы туда его не перенести?
2. Вас точно устроят те значения полей, которые вы явно не установили? Кстати, какие они будут?

2021-11-17 13:00 UTC, IEHIQ commented on main.c
> +    nrfx_gpiote_in_config_t button_config;
1. Я перенёс переменные в функцию, но в таком случае при инициализации структуры с конфигурацией сразу при объявлении и использовании её в качестве параметра в nrfx_gpiote_in_init, компилятор жалуется на неё как на 'unused variable' (я это решил, разделив объявление и инициализацию, и это работает, но ощущается как костыль конечно)
2. Что касается этих значений (они должны быть false по идее), то тут я просто не знаю, какие значения стоит использовать в данном случае

2021-11-22 08:04 UTC, Diadlo commented on button.h
> +#define DOUBLE_CLICK_DELAY 100000
Тут тоже рекомендую добавить префикс или суффикс с размерностью данных

2021-11-22 10:56 UTC, Diadlo approved these changes

2021-11-22 16:18 UTC, merged